# Pakai image Node.js official
FROM node:20-alpine

# Set working directory di dalam container
WORKDIR /app

# Copy file package.json dan package-lock.json
COPY package*.json ./

# Install dependencies (gunakan npm ci supaya konsisten)
RUN npm install

# Copy semua source code ke dalam container
COPY . .

# Expose port Vite (default 5173)
EXPOSE 5173

# Command default untuk dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]